#ifndef _GET_REGISTER_H_
#define _GET_REGISTER_H_

#include "def/typedef.h"
#include "processor.h"

reg_t processor_get_zero(void);
reg_t processor_get_ra(void);
reg_t processor_get_sp(void);
reg_t processor_get_gp(void);
reg_t processor_get_tp(void);
reg_t processor_get_t0(void);
reg_t processor_get_t1(void);
reg_t processor_get_t2(void);
reg_t processor_get_fp(void);
reg_t processor_get_s1(void);
reg_t processor_get_a0(void);
reg_t processor_get_a1(void);
reg_t processor_get_a2(void);
reg_t processor_get_a3(void);
reg_t processor_get_a4(void);
reg_t processor_get_a5(void);
reg_t processor_get_a6(void);
reg_t processor_get_a7(void);
reg_t processor_get_s2(void);
reg_t processor_get_s3(void);
reg_t processor_get_s4(void);
reg_t processor_get_s5(void);
reg_t processor_get_s6(void);
reg_t processor_get_s7(void);
reg_t processor_get_s8(void);
reg_t processor_get_s9(void);
reg_t processor_get_s10(void);
reg_t processor_get_s11(void);
reg_t processor_get_t3(void);
reg_t processor_get_t4(void);
reg_t processor_get_t5(void);
reg_t processor_get_t6(void);
reg_t processor_get_ft0(void);
reg_t processor_get_ft1(void);
reg_t processor_get_ft2(void);
reg_t processor_get_ft3(void);
reg_t processor_get_ft4(void);
reg_t processor_get_ft5(void);
reg_t processor_get_ft6(void);
reg_t processor_get_ft7(void);
reg_t processor_get_fs0(void);
reg_t processor_get_fs1(void);
reg_t processor_get_fa0(void);
reg_t processor_get_fa1(void);
reg_t processor_get_fa2(void);
reg_t processor_get_fa3(void);
reg_t processor_get_fa4(void);
reg_t processor_get_fa5(void);
reg_t processor_get_fa6(void);
reg_t processor_get_fa7(void);
reg_t processor_get_fs2(void);
reg_t processor_get_fs3(void);
reg_t processor_get_fs4(void);
reg_t processor_get_fs5(void);
reg_t processor_get_fs6(void);
reg_t processor_get_fs7(void);
reg_t processor_get_fs8(void);
reg_t processor_get_fs9(void);
reg_t processor_get_fs10(void);
reg_t processor_get_fs11(void);
reg_t processor_get_ft8(void);
reg_t processor_get_ft9(void);
reg_t processor_get_ft10(void);
reg_t processor_get_ft11(void);
reg_t processor_get_pc(void);

#endif