#ifndef _SET_REGISTER_H_
#define _SET_REGISTER_H_

#include "def/typedef.h"
#include "processor.h"

void processor_set_zero(reg_t);
void processor_set_ra(reg_t);
void processor_set_sp(reg_t);
void processor_set_gp(reg_t);
void processor_set_tp(reg_t);
void processor_set_t0(reg_t);
void processor_set_t1(reg_t);
void processor_set_t2(reg_t);
void processor_set_fp(reg_t);
void processor_set_s1(reg_t);
void processor_set_a0(reg_t);
void processor_set_a1(reg_t);
void processor_set_a2(reg_t);
void processor_set_a3(reg_t);
void processor_set_a4(reg_t);
void processor_set_a5(reg_t);
void processor_set_a6(reg_t);
void processor_set_a7(reg_t);
void processor_set_s2(reg_t);
void processor_set_s3(reg_t);
void processor_set_s4(reg_t);
void processor_set_s5(reg_t);
void processor_set_s6(reg_t);
void processor_set_s7(reg_t);
void processor_set_s8(reg_t);
void processor_set_s9(reg_t);
void processor_set_s10(reg_t);
void processor_set_s11(reg_t);
void processor_set_t3(reg_t);
void processor_set_t4(reg_t);
void processor_set_t5(reg_t);
void processor_set_t6(reg_t);
void processor_set_ft0(reg_t);
void processor_set_ft1(reg_t);
void processor_set_ft2(reg_t);
void processor_set_ft3(reg_t);
void processor_set_ft4(reg_t);
void processor_set_ft5(reg_t);
void processor_set_ft6(reg_t);
void processor_set_ft7(reg_t);
void processor_set_fs0(reg_t);
void processor_set_fs1(reg_t);
void processor_set_fa0(reg_t);
void processor_set_fa1(reg_t);
void processor_set_fa2(reg_t);
void processor_set_fa3(reg_t);
void processor_set_fa4(reg_t);
void processor_set_fa5(reg_t);
void processor_set_fa6(reg_t);
void processor_set_fa7(reg_t);
void processor_set_fs2(reg_t);
void processor_set_fs3(reg_t);
void processor_set_fs4(reg_t);
void processor_set_fs5(reg_t);
void processor_set_fs6(reg_t);
void processor_set_fs7(reg_t);
void processor_set_fs8(reg_t);
void processor_set_fs9(reg_t);
void processor_set_fs10(reg_t);
void processor_set_fs11(reg_t);
void processor_set_ft8(reg_t);
void processor_set_ft9(reg_t);
void processor_set_ft10(reg_t);
void processor_set_ft11(reg_t);
void processor_set_pc(reg_t);

#endif