#ifndef _SET_REGISTER_H_
#define _SET_REGISTER_H_

#include "def/typedef.h"

void processor_set_zero(uintptr);
void processor_set_ra(uintptr);
void processor_set_sp(uintptr);
void processor_set_gp(uintptr);
void processor_set_tp(uintptr);
void processor_set_t0(uintptr);
void processor_set_t1(uintptr);
void processor_set_t2(uintptr);
void processor_set_fp(uintptr);
void processor_set_s1(uintptr);
void processor_set_a0(uintptr);
void processor_set_a1(uintptr);
void processor_set_a2(uintptr);
void processor_set_a3(uintptr);
void processor_set_a4(uintptr);
void processor_set_a5(uintptr);
void processor_set_a6(uintptr);
void processor_set_a7(uintptr);
void processor_set_s2(uintptr);
void processor_set_s3(uintptr);
void processor_set_s4(uintptr);
void processor_set_s5(uintptr);
void processor_set_s6(uintptr);
void processor_set_s7(uintptr);
void processor_set_s8(uintptr);
void processor_set_s9(uintptr);
void processor_set_s10(uintptr);
void processor_set_s11(uintptr);
void processor_set_t3(uintptr);
void processor_set_t4(uintptr);
void processor_set_t5(uintptr);
void processor_set_t6(uintptr);
void processor_set_ft0(uintptr);
void processor_set_ft1(uintptr);
void processor_set_ft2(uintptr);
void processor_set_ft3(uintptr);
void processor_set_ft4(uintptr);
void processor_set_ft5(uintptr);
void processor_set_ft6(uintptr);
void processor_set_ft7(uintptr);
void processor_set_fs0(uintptr);
void processor_set_fs1(uintptr);
void processor_set_fa0(uintptr);
void processor_set_fa1(uintptr);
void processor_set_fa2(uintptr);
void processor_set_fa3(uintptr);
void processor_set_fa4(uintptr);
void processor_set_fa5(uintptr);
void processor_set_fa6(uintptr);
void processor_set_fa7(uintptr);
void processor_set_fs2(uintptr);
void processor_set_fs3(uintptr);
void processor_set_fs4(uintptr);
void processor_set_fs5(uintptr);
void processor_set_fs6(uintptr);
void processor_set_fs7(uintptr);
void processor_set_fs8(uintptr);
void processor_set_fs9(uintptr);
void processor_set_fs10(uintptr);
void processor_set_fs11(uintptr);
void processor_set_ft8(uintptr);
void processor_set_ft9(uintptr);
void processor_set_ft10(uintptr);
void processor_set_ft11(uintptr);
void processor_set_pc(uintptr);

#endif